### ISSUE TITLE
Do you have any plans to implement the year/month selection function?

### ISSUE THREAD

**Issue by JangCool** [wakirin/Litepicker#215] opened 2021-03-16 02:19 UTC
Do you have any plans to implement the year/month selection function?
I thought there was, but there is no.

There is a person who asked the same question below.

#193

**Comment by wakirin** [comment] 2021-03-26 12:47
As I said in #193:

> Perhaps it will be like a plugin later.

Currently there is no plans for it.

duplicate of #193

**Closed as completed by wakirin** 2021-03-26 12:47 UTC
