### ISSUE TITLE
Select specific dates within calendar

### ISSUE THREAD

**Issue by ninetyninew** [wakirin/Litepicker#127] opened 2020-09-02 18:32 UTC
**Is your feature request related to a problem? Please describe.**
Is there a way to use the litepicker to select specific days in a similar way to this: https://codepen.io/ranjith555/pen/OyKjjm ?

**Describe the solution you'd like**
A way to select specific dates within the calendar and the input field comma separates the dates.

**Describe alternatives you've considered**
Using Datepicker for Bootstrap however this is best suited to Bootstrap based websites due to the styling of the calendar it requires.

**Comment by wakirin** [comment] 2021-01-20 12:49
duplicate of #115

**Closed by wakirin** 2021-01-20 12:49 UTC
