### ISSUE TITLE
Option to disable styling alltogether

### ISSUE THREAD

**Issue by xaddict** [wakirin/Litepicker#83] opened 2020-05-14 07:11 UTC
**Is your feature request related to a problem? Please describe.**
I would like to do the complete styling myself.

**Describe the solution you'd like**
The easiest way would be a dynamic import in litepicker for the css that you can disable through settings. So if `options.usecss = false` the import doesn't happen.
Or maybe a variable that holds all the css that looks at a setting before it is added to the DOM as an inline stylesheet.

**Describe alternatives you've considered**
The npm package doesn;t hold any source files so I can't just load the original and not the css. Also, the css is inside the javascript instead of an import which makes it harder to extract the information.

**Comment by wakirin** [comment] 2020-05-14 08:42
Duplicate of #13

**Comment by chiiya** [comment] 2020-05-14 09:46
Unfortunate. I also can't use this package until the CSS is bundled separately.

**Comment by wakirin** [comment] 2020-05-14 10:25
Well, if  for many this is really problem, I'll add a feature to disable the `style` tag in the head.

**Comment by chiiya** [comment] 2020-05-14 12:10
Thanks! That would be really appreciated. I think ideally the CSS would be optional and bundled entirely separately since otherwise the JS bundle will be bloated with unnecessary code. Ultimately packages for these low-level UI components are used for their functionality and more often than not the styles need to be adjusted to the specific style guide requirements. Examples of other similar packages that do this well: `embla-carousel`, `choices.js`.

**Comment by wakirin** [comment] 2020-05-14 12:26
> I think ideally the CSS would be optional and bundled entirely separately since otherwise the JS bundle will be bloated with unnecessary code.

I didn't planned to change the current behaviour.
The file `js` will be still as single file (js code, css), but I'll add an option for prevent include the `style to the `head`.

**Comment by wakirin** [comment] 2020-05-18 07:25
Updated v1.4.4

https://wakirin.github.io/Litepicker/#anchor-no-css

**Closed** 2020-05-18 15:39 UTC
Labels: enhancement
