### ISSUE TITLE
Unable to disable datepicker

### ISSUE THREAD

**Issue by harrington101** [wakirin/Litepicker#190] opened 2021-02-17 16:49 UTC
When I create a datepicker and set the input element to disabled the datepicker still opens and allows the user to choose a different date.

**Comment by challamzinniagroup** [comment] 2021-02-18 18:09
@harrington101 I had a similar need - and ended up with a bit of a workaround. More info can be found on my (now closed) issue here: https://github.com/wakirin/Litepicker/issues/184

In short, I am capturing the `show` event and immediately calling `hide` - this is less than ideal but got me to the place I needed to be.

**Comment by harrington101** [comment] 2021-02-18 18:18
Thanks. That is what I ended up doing and it worked. I agree it's not the best way but it accomplished the task.
________________________________

**Comment by wakirin** [comment] 2021-02-19 10:12
In the next release, disabled inputs will not display the calendar when clicked.

**Comment by challamzinniagroup** [comment] 2021-02-19 12:30
@wakirin Great news, thanks so much!

**Comment by harrington101** [comment] 2021-02-19 13:41
Great news! Thank you.
________________________________

**Comment by scott-fisher-iii** [comment] 2021-02-19 13:45
Beautiful. Now I can remove my on 'show' hack

**Comment by wakirin** [comment] 2021-02-19 14:30
fixed in 2.0.7

https://jsfiddle.net/a6c4msh1/

**Closed by wakirin** 2021-02-19 14:30 UTC

**Comment by challamzinniagroup** [comment] 2021-02-25 14:09
> fixed in 2.0.7
> 
> https://jsfiddle.net/a6c4msh1/

I just updated to latest (2.0.0 now) to get this change, and it seems to have broken all my datepickers. I am getting a
```
Cannot read property 'dataset' on null
```
exception on all my previously working datepickers. Any thoughts?

**Comment by wakirin** [comment] 2021-02-25 14:12
https://jsfiddle.net/06oyj51v/

I don't see problem with 2.0.9
Make sure you provide the item exists in the Litepicker settings.

**Comment by challamzinniagroup** [comment] 2021-02-25 14:20
These are all Litpickers that worked an hour ago prior to the upgrade. The elements exist lol.

**Comment by wakirin** [comment] 2021-02-25 14:24
I don't have telepathy skills, instead of your "lol" you are better off providing a jsfiddle with your problem.
Thanks.

**Comment by challamzinniagroup** [comment] 2021-02-25 14:31
This is a 3 month in-progress project. I have far too much intertwined here to be interested in spending time creating fiddle to help debug right now.

The date pickers were literally working an hour ago, prior to the upgrade from 2.0.6 to 2.0.9. Your "make sure the element exists" response was laughable (hence the lol). It was akin to a customer service rep asking "Is it plugged in?". 

I have reverted to 2.0.6, they are working again. Thanks.

**Comment by wakirin** [comment] 2021-02-25 14:44
Well, I don't know your level of knowledge.
So I assumed the first thing that could be the cause.

As I said above, I see no problem with 2.0.9 (https://jsfiddle.net/06oyj51v/)
Your Litepicker configuration can also help detect the problem, but if you not interested in helping debug the problem that's ok.
Good luck.

**Comment by harrington101** [comment] 2021-02-25 15:05
> This is a 3 month in-progress project. I have far too much intertwined here to be interested in spending time creating fiddle to help debug right now.
> 
> The date pickers were literally working an hour ago, prior to the upgrade from 2.0.6 to 2.0.9. Your "make sure the element exists" response was laughable (hence the lol). It was akin to a customer service rep asking "Is it plugged in?".
> 
> I have reverted to 2.0.6, they are working again. Thanks.

I get that creating a fiddle can be time consuming. Can you post your call to litepicker and any related functions here? Maybe that will help.

**Comment by scott-fisher-iii** [comment] 2021-02-25 15:10
Pro Tip: Take @wakirin 's jsfiddle, input your binding code, click save and you have your own fiddle.

You have got to give us something to go on. Clearly this version is working for others.

**Comment by challamzinniagroup** [comment] 2021-02-25 15:26
The initialization code under v2.0.9 that is not working:
```
this.datepickerRequired = new Litepicker({
  dropdowns: {
    maxYear: null,
    minYear: 1990,
    months: true,
    years: true
  },
  element: document.getElementById('requiredDate'),
  format: 'MM/DD/YYYY',
  maxDate: new Date(),
  singleMode: true,
  startDate: this.f.requiredDate.value
});
 ```
 
 The initialization code under v2.0.9 that *is* working:
 ```
Promise.resolve(null).then(() => {
  this.datepickerRequired = new Litepicker({
    dropdowns: {
       maxYear: null,
       minYear: 1990,
       months: true,
       years: true
     },
     element: document.getElementById('requiredDate'),
     format: 'MM/DD/YYYY',
     maxDate: new Date(),
     singleMode: true,
     startDate: this.f.requiredDate.value
   });
 });
 ```
    
    This is under an Angular 11 app. The fact that it is working under the pseudo `Promise` wait indicates that there is an issue with the Angular digest cycle timing. Again, this worked prior to my upgrading of the Litepicker from 2.0.6 to 2.0.9 - so I'm not sure how this could be causing issue.
    
    For those familiar with Angular, this is all being triggered from the `ngOnInit` event, so the DOM has been created, change detection has occurred, and so on.

**Comment by challamzinniagroup** [comment] 2021-02-25 15:28
Just to add, the `this.f` is a (pretty typical) `getter` func for the Angular reactive form control collection.

**Comment by challamzinniagroup** [comment] 2021-02-25 15:44
I've narrowed it a little further, probably to a fair enough resolution at this point.

I have the root element disabled on page load (my reason for upgrading to the newer version was to have this work as a toggle switch for the Litepicker itself), and am then running a series of logic checks that, in some cases, will enable the input (and then also the Litepicker). I believe the timing of this enable is what is somehow causing the Litepicker to not be able to see the element during the same digest cycle that it is being initialized? I'm not sure that makes sense, as a `document.getElementById` should pull the element whether it is enabled or not...

But when I perform things in reverse order (begin with the element enabled and then conditionally disable), I no longer receive the `Cannot read property 'dataset' of null` exception.

I do not think this is any kind of bug or issue in the Litepicker code (or update), but rather in how I was toggling the element enabled/disabled and the timing of that, versus the timing of the Litepicker initialization, and versus the timing of the Angular digest cycle.

Thanks everyone for having a quick moment of interest - and apologies @wakirin - I do not mean to come across as not wanting to help at all. It's why I post on here in the first place. I'm just very short on spare time lately. :)

**Comment by scott-fisher-iii** [comment] 2021-02-25 15:49
> I'm just very short on spare time lately. :)

Ah, the life of a developer.
