### ISSUE TITLE
Tabbing away from the input doesn't hide / cancel the picker

### ISSUE THREAD

**Issue by oodavid** [wakirin/Litepicker#76] opened 2020-05-06 19:47 UTC
As-per the title.

I know from experience this is a tough feature since a blur event isn't much use (the user is probably interacting with the calendar popup) - I think using `activeElement` (possibly with a timeout) could be a neat way to know whether to hide the picker, ie:

```js
function hideIfBlurred(){
    var usingPicker = isDescendant(pickerElement, document.activeElement);
    var usingElement = isDescendant(targetElement, document.activeElement);
    if(!usingPicker && !usingElement){
        hide();
    }
}

function isDescendant(parent, child) {
     var node = child.parentNode;
     while (node != null) {
         if (node == parent) {
             return true;
         }
         node = node.parentNode;
     }
     return false;
}
```

**Comment by wakirin** [comment] 2020-05-07 07:47
But why should we hide the picker on blur ?
I think it is not necessary.
If the developer wants to hide it on a blur event, the developer can implement this function on his side.

**Comment by joaomvfsantos** [comment] 2020-05-07 15:43
I'm struggling with this too. I tried doing it on a blur event and call the `.hide()` method, however this causes the blur event to trigger when I select a day, which effectively cancels the date selection (most probably because the blur event fires first than the click event on the day).

Consider this: If I have a date picker opened, click on another input field (any) the date picker closes. If it tab navigate out of the input date-picker it should also close the date picker.

**Comment by wakirin** [comment] 2020-05-09 06:07
I made it as additional module because not everyone needs this feature.
https://github.com/wakirin/litepicker-module-navkeyboard

An example is here: https://jsfiddle.net/894Lsw21/1/

**Comment by joaomvfsantos** [comment] 2020-05-11 10:18
Thanks for this @wakirin I tried your fiddle out. It works nice on Chrome, but Safari and Firefox keeps looping between the first input, the second input and the "month back arrow". Can you confirm this?

**Comment by oodavid** [comment] 2020-05-11 20:10
> But why should we hide the picker on blur ?
> I think it is not necessary.

This is why:

![tabbing](https://user-images.githubusercontent.com/46879/81606680-675cca80-93cb-11ea-89d5-bc8dbe2c84f0.gif)

> If the developer wants to hide it on a blur event, the developer can implement this function on his side.

Thanks for this. I'd upgraded from Lightpicker and that had an issue whereby interacting with the popup would make the input lose focus, I see this is no longer the case. I've updated my implementation to hide on blur. Easy enough to do!

Happy to close, maybe a one-liner in the docs would help others out.

**Comment by oodavid** [comment] 2020-05-11 22:12
> Thanks for this. I'd upgraded from Lightpicker and that had an issue whereby interacting with the popup would make the input lose focus, I see this is no longer the case. I've updated my implementation to hide on blur. Easy enough to do!

I spoke too soon - this issue is still there, the moment you interact with the calendar, the associated element loses focus. Using anything like `onblur="hideTheCalendar()"` makes the widget unusable.

**Comment by wakirin** [comment] 2020-05-12 18:18
@oodavid 
Sorry, I don't understand what is the problem now ?
You have include `litepicker-module-navkeyboard` and also use `onblur="hideTheCalendar()"` too ?

@joaomvfsantos 
Yes, I can confirm this problem. I'll try to fix in the next release.

**Comment by wakirin** [comment] 2020-05-14 09:18
@joaomvfsantos 
in v0.1.0 should be fixed, try to update `litepicker-module-navkeyboard`.

https://jsfiddle.net/pdg5mz7o/

**Closed** 2020-05-18 05:52 UTC
Labels: enhancement
