### ISSUE TITLE
Deselect a date in a selected range

### ISSUE THREAD

**Issue by ghost** [wakirin/Litepicker#130] opened 2020-09-09 14:22 UTC
I was wondering if it is possible to deselect a day in a selected range, and export all other dates as an array.
If there is not such a feature yet, it could be great to have such a thing. 
It could be done by a tooltip on hover saying `Deselect`.

**Comment by wakirin** [comment] 2021-01-20 12:50
duplicate of #115

**Closed by wakirin** 2021-01-20 12:50 UTC
