### ISSUE TITLE
Multiple date selection options like bootstrap

### ISSUE THREAD

**Issue by etwordpress01** [wakirin/Litepicker#164] opened 2021-01-22 13:25 UTC
Hello, Thank you so much for the very light weight and awesome datepicker. 

We are using this, in an official project which is a marketplace like upwork or fiverr. We are facing to use this datepicker as multiple date selection. We are managing time slots for the meetings within the platform. So we basically needs to select multiple dates for the meetings to create time slots.

![10](https://user-images.githubusercontent.com/31212934/105495711-509e9f80-5cde-11eb-89a7-2c91085651c1.png)

We would like to stick on that because all over the site we are using this datepicker. We just facing an issue to select multiple dates like bootstrap does.

![11](https://user-images.githubusercontent.com/31212934/105495918-952a3b00-5cde-11eb-8785-7f587156a6cc.png)

Is their any callback function? so we can create separate extension to get this done. Can you please consider this feature in near future?? Or any tip to create an extension which could work like bootstrap multiple datepicker. 

This will be a huge update in this datepicker if you can consider or guide us ? so our development team can create an extension for this feature.

Looking forward to hearing from you
Any other help would be appreciated. 

Thanks again

**Comment by etwordpress01** [comment] 2021-01-25 05:03
@wakirin Can you please help me on this?

**Comment by wakirin** [comment] 2021-01-25 06:13
Currently not supported.
I think you can try doing this with v2 and a plugin. See examples: https://github.com/wakirin/Litepicker/tree/v2/src/plugins
v2 is currently in beta.
I am planning on making plugin for multiple choice, but I can't say when yet.

Also the current issue is duplicate of #115

**Closed by wakirin** 2021-01-25 06:13 UTC
