### ISSUE TITLE
Clear start or end date in range mode

### ISSUE THREAD

**Issue by depsimon** [wakirin/Litepicker#146] opened 2020-11-17 12:36 UTC
**Is your feature request related to a problem? Please describe.**

I have multiple use cases where the user should be able to clear a start or end date or both.
In these scenarios the user should be able to select only a start date or only a end date.

For instance, we have resources that require to have a start date, but the end date can be null.

**Describe the solution you'd like**

`picker.setDateRange()`, `picker.setStartDate()` and `picker.setEndDate()` should allow for null values.

Alternatives could be to implement new `clearStartDate()` and `clearEndDate()` methods.

The result should be a date picker where I can select only a startDate and trigger onSelect which will have a valid start date & a null end date.

**Describe alternatives you've considered**

I tried adding prototype functions like this
```javascript
Litepicker.prototype.clearEndDate = function () {
  this.options.endDate = null
  this.options.elementEnd.value = null
}
Litepicker.prototype.clearStartDate = function () {
  this.options.startDate = null
  this.options.elementStart.value = null
}
```

This clears the date & force the element value to be null but when I clear the endDate open the picker, there is no selected start date.

**Comment by depsimon** [comment] 2020-11-17 14:15
I managed to get something somewhat functionnal.

This onShow handler makes the repicking work after you clear a date.

```js
onShow: function () {
  if (!this.options.startDate || !this.options.endDate) {
    if (this.options.startDate) {
      this.options.endDate = this.options.startDate
    }
    if (this.options.endDate) {
      this.options.startDate = this.options.endDate
    }
  }
}
```

Also to make it work at initial rendering I added this code after the initialization of the Litepicker for when I initially have a nul date.

```
const picker = new Litepicker({...})

if (!startDate || !endDate && startDate !== endDate) {
  picker.setOptions({
    startDate: startDate ? startDate : endDate,
    endDate: startDate ? startDate : endDate,
  })
  
  if (startDate) {
    picker.options.elementEnd.value = null
  } else if (endDate) {
    picker.options.element.value = null
  }
}
```

Scenario : 

- startDate = 2020-11-17
- endDate = null

On initial load:
- it'll set the endDate to 2020-11-17 so when we open the picker it allows a range from the startDate
- it'll reset the value of the elementEnd element so that the input is empty

Scenario : 

- startDate = 2020-11-17
- endDate = 2020-12-30

When user clicks "Clear end date":
- it'll set the endDate value to null
- it'll set the elementEnd value to null

When user opens the picker again:
- it'll set the endDate to 2020-11-17 so when we open the picker it allows a range from the startDate

**Comment by wakirin** [comment] 2021-01-31 06:41
duplicate of #52

**Closed by wakirin** 2021-01-31 06:41 UTC
